### ISSUE TITLE
Failed to download the videos

### ISSUE THREAD

**Issue by qiruiw** [google-research/cad-estate#3]
Thanks for you great efforts in releasing the dataset!

I was able to download and extract the CAD-Estate annotations.
But I ran into the following issues when downloading the videos
```
$ PYTHONPATH=src python -m cad_estate.download_and_extract_frames --cad_estate_dir="$(realpath data/)" --skip_extract 
Loading frame timestamps:   0%|                                                                                                                            | 0/21452 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/localhome/qiruiw/miniconda3/envs/estate/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/localhome/qiruiw/miniconda3/envs/estate/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/cs/3dlg-project/3dlg-hcvc/rlsd/data/cad_estate/src/cad_estate/download_and_extract_frames.py", line 267, in <module>
    main()
  File "/cs/3dlg-project/3dlg-hcvc/rlsd/data/cad_estate/src/cad_estate/download_and_extract_frames.py", line 221, in main
    video_timestamps = [
  File "/cs/3dlg-project/3dlg-hcvc/rlsd/data/cad_estate/src/cad_estate/download_and_extract_frames.py", line 222, in <listcomp>
    get_video_timestamps(v)
  File "/cs/3dlg-project/3dlg-hcvc/rlsd/data/cad_estate/src/cad_estate/download_and_extract_frames.py", line 135, in get_video_timestamps
    video_id = ann_json["video_id"]
KeyError: 'video_id'
Loading frame timestamps:   0%|                                                                                                                            | 0/21452 [00:00<?, ?it/s]
```

It seems that the annotation json files don't contain the required field "video_id".
Can you help check it?

**Comment by kmaninis** [comment]
Hi, thank you for your interest and your kind words.

This was a typos, should be fixed with https://github.com/google-research/cad-estate/commit/396babd20efe543aa6a254492de71cbb248de457

Alternatively, you can download the already extracted frames from TUM:
https://kaldir.vc.in.tum.de/cadestate/readme.txt

Let me know if this solves your issue.

**Comment by ZheningHuang** [comment]
Thank you for your effort in creating this dataset.

Does the content of [this README file](https://kaldir.vc.in.tum.de/cadestate/readme.txt) correspond to the following instructions?


### Download the Videos
To download the videos, use the following commands:
```bash
cd ${WORKDIR}/cad_estate; pyenv shell cad_estate
PYTHONPATH=src python -m cad_estate.download_and_extract_frames \
  --cad_estate_dir="$(realpath data/)" \
  --skip_extract
```

This will download the videos into `${WORKDIR}/cad_estate/data/raw_videos` and log the results into:
```
${WORKDIR}/cad_estate/data/log_<date-and-time>.txt
${WORKDIR}/cad_estate/data/download_results_<date-and-time>.csv
```
The first log captures all Python `logging` information, and the second one contains the download status for each video. `<date-and-time>` represents the timestamp when the program started.

### Extract the Video Frames
The next step is to extract the video frames using the following commands:
```bash
cd ${WORKDIR}/cad_estate; pyenv shell cad_estate
PYTHONPATH=src python -m cad_estate.download_and_extract_frames \
  --cad_estate_dir="$(realpath data/cad_estate)" \
  --parallel_extract_tasks 4 \
  --skip_download
```

In the command above, `parallel_extract_tasks` specifies the number of `ffmpeg` instances to run in parallel (4 is recommended for a 12-core CPU). Similar to the download step, this script produces two logs:
```
${WORKDIR}/cad_estate/data/log_<date-and-time>.txt
${WORKDIR}/cad_estate/data/process_results_<date-and-time>.csv
```
